### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mr-shubhshar** [mr-shubhshar/staticwebsite#2]
### TODO

- [ ] Add Particles.js to the background
- [x] Add Google Analytics code
- [ ] Authenticate with Google Analytics account
